config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete '/logout', to:'sessions#destroy' #<-- handle
  get '/dashboard/:id', to:'users#dashboard'
  get '/orders/change_status/:id', to:'orders#change_status' 
  resources :users
  get '/res_user_reg', to:'restaurant_user_registrations#new'
  post '/res_user_reg', to:'restaurant_user_registrations#create'
  get '/cart/add/:id', to:'cart#add'
  get '/cart/clear', to:'cart#clear'
  get '/cart/remove/:id', to:'cart#remove'
  get '/cart/order', to: 'cart#order'
  resources :restaurants do
    resources :items
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer bg-light text-black-50">
	<div class="container text-center">
        <p>
            &copy Food Delivery Site
        </p>
    </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
    <a class="navbar-brand" href="<%= user_logged_in? ? '/dashboard/'+current_user.id.to_s : root_path%>">Food Delivery Site</a> <!-- based upon session give link -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <% if !user_logged_in? %>
                <li class="nav-item">
                    <a class="nav-link" href="<%= login_path %>">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<%= new_user_path+"?role=U"%>">Sign Up</a>
                </li>
            <% else %> 
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%= current_user.name%>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <%= link_to "Dashboard", "/dashboard/"+current_user.id.to_s, class: "dropdown-item"%>
                        <%= link_to "Profile", current_user, class:"dropdown-item"%>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="<%= logout_path %>" data-method="delete">Log Out</a>
                    </div>
                </li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/_normal-user-profile.html.erb
<br>
<h3 class="mb-3">User Profile</h3>
<div class="row">
    <div class="col-md-6">
        <h6>Name</h6>
        <h5><%= @user.name%></h5>
        <h6>Email</h6>
        <h5><%= @user.email%></h5>
        <h6>Phone</h6>
        <h5><%= @user.phone%></h5>
    </div>
</div>

app/views/layouts/_restaurant-user-registration-form.html.erb
<%= form_for @registration, url: res_user_reg_path do |f|%>
            <div class="form-group">
                    <%= f.label :name%>
                    <%= f.text_field :name, class:"form-control", placeholder:"Enter Name", required:true%>
            </div>
            <div class="form-group">
                <%= f.label :email%>
                <%= f.email_field :email, class:"form-control", placeholder:"Enter Email",required:true%>
            </div>

            <div class="form-group">
                <%= f.label :phone %>
                <%= f.telephone_field :phone, class:"form-control ", placeholder:"Enter Phone Number",required:true%>
            </div>
            <div class="text-center"><small id="passwordHelpInline" class="text-muted">Restaurant Details</small></div>
            <div class="form-group">
                <%= f.label :restaurant_name%>
                <%= f.text_field :restaurant_name, class:"form-control", placeholder:"Enter Restaurant Name",required:true%>
            </div>
            <div class="form-group">
                <%= f.label :street %>
                <%= f.telephone_field :street, class:"form-control ", placeholder:"Enter Street",required:true%>
            </div>
            
            <div class="form-row">
                <div class="form-group col-md-4">
                    <%= f.label :city%>
                    <%= f.text_field :city, class:"form-control", placeholder:"Enter City",required:true%>
                </div>

                <div class="form-group col-md-4">
                    <%= f.label :pincode%>
                    <%= f.text_field :pincode, class:"form-control", placeholder:"Enter pincode",required:true%>
                </div>

                <div class="form-group col-md-4">
                    <%= f.label :state%>
                    <%= f.text_field :state, class:"form-control", placeholder:"Enter State",required:true%>
                </div>
            </div>

            <div class="form-row">
            <div class="form-group col-md-6">
                <%= f.label :password%>
                <%= f.password_field :password, class:"form-control", placeholder:"Enter Password",required:true%>
            </div>

            <div class="form-group col-md-6">
                <%= f.label :password_confirmation, "Password Confirmation" %>
                <%= f.password_field :password_confirmation, class:"form-control", placeholder:"Confirm Password",required:true%>
            </div>
            </div>
            
            <%= hidden_field_tag 'role', params[:role] %>
            
            <div class="form-group">
                <%= f.submit "Sign Up", class:"btn btn-primary btn-block" %>
            </div>
<% end %>

app/views/layouts/_user-edit-profile.html.erb
<br>
<h3 class="mb-3">Edit Profile</h3>
    <%if @user.errors.any? %>
            <%= render 'layouts/user-error' %>
    <% end %>

    <%= form_with(model: @user, local: true) do |f| %>
    <div class="form-group row">
        <div class="col-md-3">
            <%= f.label :name, class:"col-form-label form-control-label"%>
        </div>
        <div class="col-md-9">
            <%= f.text_field :name, class:"form-control", value:@user.name,required:true%>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-3">
            <%= f.label :email, class:"col-form-label form-control-label" %>
        </div>
        <div class="col-md-9">
            <%= f.email_field :email, class:"form-control", value:@user.email,required:true%>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-3">
            <%= f.label :phone, class:"col-form-label form-control-label"%>
        </div>
        <div class="col-md-9">
            <%= f.text_field :phone, class:"form-control", values:@user.phone,required:true%>
        </div>
    </div>
 
    <div class="form-group row">
        <div class="col-md-3">
            <%= f.label :address, class:"col-form-label form-control-label"%>
        </div>
        <div class="col-md-9">
            <%= f.text_field :street ,class:"form-control",placeholder:"Street", value:@user.address.nil? ? "":@user.address.street,required:true%>
        </div>
    </div>
 
    <div class="form-group row">
        <div class="col-md-3">
            <label class="col-form-label form-control-label"></label>
        </div>
        <div class="col-md-3">
            <%= f.text_field :city, class:"form-control", placeholder:"City", value:@user.address.nil? ? "" : @user.address.city,required:true%>
        </div>
        <div class="col-md-3">
            <%= f.text_field :pincode, class:"form-control", placeholder:"Pincode",value:@user.address.nil? ? "" : @user.address.pincode,required:true%>
        </div>
        <div class="col-md-3">
            <%= f.text_field :state, class:"form-control", placeholder:"State", value:@user.address.nil? ? "" : @user.address.state,required:true%>
        </div>
    </div>
    
    <div class="form-group row">
        <div class="col-md-3">
            <%= f.label :image, class:"col-form-label form-control-label"%>
        </div>
        <div class="col-md-9">
           <%= f.file_field :image%>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-3">
            <%= f.label :password, class:"col-form-label form-control-label"%>
        </div>
        <div class="col-md-9">
            <%= f.password_field :password, class:"form-control", value:"dummyvalue",required:true%>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-3">
            <%= f.label :confirm_password, class:"col-form-label form-control-label"%>
        </div>
        <div class="col-md-9">
           <%= f.password_field :confirm_password, class:"form-control", value:"dummyvalue",required:true%>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-3">
            <label class="col-form-label form-control-label"></label>
        </div>
        <div class="col-md-9">
            <input type="reset" class="btn btn-secondary" value="Cancel">
            <input type="submit" class="btn btn-primary" value="Save Changes">
        </div>
    </div>
    <% end %>

app/views/layouts/_user-error.html.erb
<div id="error_explanation">
    <div class="alert alert-danger">
        The form contains <%= pluralize(@user.errors.count, "error")%>.
    </div>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
</div>

app/views/layouts/_user-profile.html.erb
<br>
<h3 class="mb-3">User Profile</h3>
<div class="row">
    <div class="col-md-6">
        <h6>Name</h6>
        <h5><%= @user.name%></h5>
        <h6>Email</h6>
        <h5><%= @user.email%></h5>
        <h6>Phone</h6>
        <h5><%= @user.phone%></h5>
        <%if @user.role == "U" && !@user.address.nil? %>
            <h6>Address</h6>
            <h5><%= @user.address.street+','+@user.address.city+','+@user.address.pincode+','+@user.address.state%></h5>
        <% elsif @user.role == "R" %>
            <h6>Restaurant Details</h6>
            <h5><%= @user.restaurant.name%></h5>
            <h5><%= @user.restaurant.address.street+','+@user.restaurant.address.city+','+@user.restaurant.address.pincode+','+@user.restaurant.address.state%></h5>
        <% end %>
    </div>
</div>

app/views/layouts/_user-registration-form.html.erb
<%= form_for(@user) do |f|%>
            <div class="form-group">
                    <%= f.label :name%>
                    <%= f.text_field :name, class:"form-control", placeholder:"Enter Name",required:true%>
            </div>
            <div class="form-group">
                <%= f.label :email%>
                <%= f.email_field :email, class:"form-control", placeholder:"Enter Email",required:true%>
            </div>

            <div class="form-group">
                <%= f.label :phone %>
                <%= f.telephone_field :phone, class:"form-control ", placeholder:"Enter Phone Number",required:true%>
            </div>

            <div class="form-group">
                <%= f.label :password%>
                <%= f.password_field :password, class:"form-control", placeholder:"Enter Password",required:true%>
            </div>

            <div class="form-group">
                <%= f.label :password_confirmation, "Password Confirmation" %>
                <%= f.password_field :password_confirmation, class:"form-control", placeholder:"Confirm Password",required:true%>
            </div>
            
            <%= hidden_field_tag 'role', params[:role] %>
            
            <div class="form-group">
                <%= f.submit "Sign Up", class:"btn btn-primary btn-block" %>
            </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodDeliverySite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="turbolinks-cache-control" content="no-cache">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!--<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.20/b-1.6.0/r-2.2.3/sc-2.0.1/sl-1.3.1/datatables.min.css"/>
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.20/b-1.6.0/r-2.2.3/sc-2.0.1/sl-1.3.1/datatables.min.js"></script><-->

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.20/datatables.min.css"/>
 
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.20/datatables.min.js"></script>

    <script src="https://js.pusher.com/5.0/pusher.min.js"></script>
  </head>

  <body>
      <%= render 'layouts/header'%>
        <% flash.each do |msg_type, msg| %>      
          <div class="toast-<%= msg_type %> toast" style="position: absolute; top: 100; right: 0;" role="alert" aria-live="assertive" aria-atomic="true" data-autohide="false">
            <div class="toast-body">
              <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <%= msg %>
            </div>
          </div>
          <script>$('.toast').toast('show')</script>
        <% end %>
        <%= yield %>
      <%= render 'layouts/footer'%>
  </body>
</html>